from __future__ import annotations

from datetime import date, datetime

from pydantic import BaseModel, ConfigDict, Field


class CaseCreate(BaseModel):
    dosya_adi: str | None = Field(default=None, max_length=255)
    esas_no: str | None = Field(default=None, max_length=100)
    karar_no: str | None = Field(default=None, max_length=100)
    mahkeme: str | None = Field(default=None, max_length=255)
    dava_konusu: str | None = Field(default=None, max_length=512)
    dava_tarihi: date | None = None
    karar_tarihi: date | None = None
    sum_human: str | None = None
    sum_model: str | None = None
    tam_olay: str | None = None
    gerekce: str | None = None
    hukum: str | None = None


class CaseUpdate(BaseModel):
    dosya_adi: str | None = Field(default=None, max_length=255)
    esas_no: str | None = Field(default=None, max_length=100)
    karar_no: str | None = Field(default=None, max_length=100)
    mahkeme: str | None = Field(default=None, max_length=255)
    dava_konusu: str | None = Field(default=None, max_length=512)
    dava_tarihi: date | None = None
    karar_tarihi: date | None = None
    sum_human: str | None = None
    sum_model: str | None = None
    tam_olay: str | None = None
    gerekce: str | None = None
    hukum: str | None = None


class CaseResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    dosya_adi: str | None
    esas_no: str | None
    karar_no: str | None
    mahkeme: str | None
    dava_konusu: str | None
    dava_tarihi: date | None
    karar_tarihi: date | None
    sum_human: str | None
    sum_model: str | None
    tam_olay: str | None
    gerekce: str | None
    hukum: str | None
    created_at: datetime


class CaseSearchResult(CaseResponse):
    """CaseResponse enriched with hybrid BM25 + cosine retrieval metadata.

    Fields
    ------
    score:
        Cosine similarity in the closed range ``[0.0, 1.0]`` (1.0 = perfect
        match).  Computed in :func:`app.crud.crud_case.search_cases` as
        ``1 − cosine_distance`` over L2-normalised embeddings.
    matched_chunk_text:
        Verbatim text of the single best-matching chunk (the one that
        produced ``score``).  Drives the "Neden bu karar getirildi?" panel
        in the UI when ENABLE_LLM_XAI is OFF.
    xai_explanation:
        Optional natural-language explanation generated by the LLM XAI
        service.  Populated only when ``settings.ENABLE_LLM_XAI`` is True;
        ``None`` otherwise.
    """

    score: float | None = None
    matched_chunk_text: str | None = None
    xai_explanation: str | None = None


class CaseSearchQuery(BaseModel):
    query: str = Field(..., min_length=1, max_length=1024)
    limit: int = Field(default=10, ge=1, le=100)


class CaseChunkResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    case_id: int
    chunk_id: str | None
    chunk_text: str | None
    created_at: datetime
